# Generated by Django 2.2 on 2021-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXRayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('croped', models.CharField(max_length=100)),
                ('upper_image', models.CharField(max_length=100)),
                ('lower_image', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'UserDentalResults',
            },
        ),
    ]
